### ISSUE TITLE
API Endpoint for Sending SMSes Using Twilio API

### ISSUE THREAD

**Issue by Olaoluwa22** [hngprojects/hng_boilerplate_java_web#10]
### Description
Implement an API endpoint for sending SMSes using the Twilio API. This endpoint should allow users to send SMS messages to specified phone numbers.

### Acceptance Criteria

- [ ] The endpoint should be accessible at POST /api/v1/sms/send.
- [ ] The endpoint should accept HTTP POST requests.
- [ ] The endpoint should send an SMS message using the Twilio API with the provided phone number and message content.
- [ ] The endpoint should return a 200 OK status code with a success message in the response body.

#### Request Example:
POST /api/v1/sms/send
Content-Type: application/json
```
{
  "phone_number": "+1234567890",
  "message": "Hello, this is a test message."
}
```

#### Response Example:
On successful sending of the SMS message, the API should return a 200 OK status code. The response body should contain a success message:
```
{
  "status": "success",
  "status_code": 200,
  "message": "SMS sent successfully."
}
```

#### Validation:

If the phone number or message content is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages:
```
{
  "status": "unsuccessful",
  "status_code": 400,
  "message": "Valid phone number and message content must be provided."
}
```

If there is an error in sending the SMS (e.g., invalid Twilio credentials, network issues), the API should return a 500 Internal Server Error status code with an appropriate message:
```
{
  "status": "unsuccessful",
  "status_code": 500,
  "message": "Failed to send SMS. Please try again later."
}
```

### Purpose
Provides a backend service that allows users to send SMS messages via the Twilio API.

### Requirements
- Develop server-side logic to send SMS messages using the Twilio API.
- Securely handle the process and comply with security standards.
- Ensure that the phone number and message content are validated and handled correctly.

### Expected Outcome
- API endpoint allows users to send SMS messages with appropriate validation and security measures.

### Tasks:
 - [ ] Define the POST /api/v1/sms/send route in the server-side application.
- [ ] Validate that the phone number and message content are provided and are in a valid format.
- [ ] Implement logic to send the SMS message using the Twilio API with the provided phone number and message content.
- [ ] Return a success message in the response body if the SMS is sent successfully.
- [ ] Handle cases where the phone number or message content is invalid, providing appropriate error messages.
- [ ] Handle cases where sending the SMS fails, providing appropriate error messages.

### Testing
- Write unit tests to validate input validation and SMS sending logic.
- Write integration tests to ensure end-to-end functionality.
- Perform security testing to ensure data protection and compliance.
