### ISSUE TITLE
[FEAT] Multi Device Login Support

### ISSUE THREAD

**Issue by githukueliud** [hngprojects/hng_boilerplate_java_web#17]
### Description

Allow users to log in from multiple devices.

### Multi-Device Login Endpoint
[POST] /api/v1/auth/login

### Multi-Device Login Support
 1. Given a request with valid user details (i.e., email, password, device information), when the user logs in, the system should allow multiple active sessions from different devices.
 2. Given a request with valid login credentials, when the user logs in from a new device, the system should track the device and manage sessions accordingly.
 3. Given a request from a previously logged-in device, when the user logs in again, the system should recognize the device and maintain session continuity.

### Request
POST /api/v1/auth/login

```
{
  "email": "String",
  "password": "String",
  "device_info": {
    "device_id": "String",
    "device_type": "String"
  }
}
```

### Succesful Response

```
{
  "access_token": "String",
  "expires_in": "Int",
  "device": {
    "device_id": "String",
    "device_type": "String"
  }
}
```

### Error Response

```
{
  "message": "String",
  "error": "String",
  "status_code": "Int"
}
```

### Token Management and Device Tracking:

**1. Session Management**
 - Given a user login request, when the user logs in from multiple devices, then the system should manage sessions for each device individually.
 - Given a device login request, when the user logs in from a new device, then the system should track the device details (deviceId, deviceType).

**2. Token Generation and Expiry**
 - Given valid login credentials, when the user logs in, then the system should generate a JWT token for each session.
 - The generated token should have an expiry time configured to 1 hour.
 - Given an expired token, when the user tries to access a protected route, then the system should return a 401 Unauthorized status.

### Accessing Protected Routes:

**Authorization Header**
  - Given a valid token in the Authorization header, when the user accesses a protected route, then the system should allow access and return the requested data.
 - Given a request without an Authorization header or with an invalid token, when the user accesses a protected route, then the system should return a 401 Unauthorized status.

### Error Handling

**Invalid Credentials**
 - When the user logs in with invalid credentials, the system should return a 401 Unauthorized status with an appropriate error message.

```
{
  "message": "Invalid credentials",
  "status_code": 401
}
```

### Expected Outcome

 - [ ] Multi-Device Login Support: Enable users to log in from multiple devices concurrently using a single set of credentials.
 - [ ] Session Management: Manage login sessions independently for each device to ensure security and session continuity.
  - [ ] Token Management: Generate JWT tokens with a 1-hour expiry upon successful login. Expired tokens trigger a 401 Unauthorized status when accessing protected routes.
  - [ ] Authorization: Control access to protected routes based on valid JWT tokens provided in the Authorization header. Invalid tokens result in a 401 Unauthorized status.
  - [ ] Error Handling: Provide clear error messages for scenarios like invalid credentials during login attempts.

### Tasks

 - [ ] Endpoint Implementation: Create a POST endpoint /api/v1/auth/login for multi-device logins.
  - [ ] Session Management: Implement logic to track and manage sessions independently for each device.
  - [ ] Token Generation and Expiry: Develop JWT token generation with 1-hour expiry and handle token expiration.
  - [ ] Authorization Mechanism: Implement middleware to validate JWT tokens for protected route access.
  - [ ] Error Handling and Response: Define and implement error handling for login failures and token validation.
  - [ ] Testing: Create unit tests for login functionality, session management, token handling, and error responses.
  - [ ] Documentation: Update API documentation for /api/v1/auth/login endpoint, payloads, responses, and error codes.
  - [ ] Integration and Deployment: Integrate feature, deploy in development environment, and document deployment procedures.

### Testing

**Unit Tests**
 - The system should have unit tests covering multi-device login logic, including successful and failed login attempts, token generation and validation, and session management for multiple devices.
