### ISSUE TITLE
[FEAT] Implement API Endpoint to SOFT DELETE a Subscription Plan

### ISSUE THREAD

**Issue by Adewale66** [hngprojects/hng_boilerplate_java_web#199]
## Description

Develop backend support to delete a subscription plan. This feature will enable admin to delete specific plans.

## Acceptance Criteria

- Subscription plans can be deleted through the API.
- All unit and integration tests pass successfully.
- Both API and user documentation are updated to reflect the new subscription plan feature.

### Error Handling:

- Log errors for invalid requests.
- Display clear error messages for invalid inputs.

## Purpose

To provide admin with the ability to delete a subscription plan.

### Requirements

- Admin must be authenticated and authorized.
- Develop server side logic to soft delete subscription plans to database.

### Expected Outcome

1. The backend should handle subscription plan deletion efficiently.
2. The system should log responses and errors properly

## Endpoints

- Endpoint: ```  DELETE /api/v1/plans/{id} ```

- #### Success Response: Delete Subscription Plan 

```json
{
  "status_code": 204,
}
```

- #### Error Response: Unauthorized Access

```json
{
  "status_code": 403,
  "error": "User is not authorized to create subscription plans."
}
```

- #### Error Response: Subscription Plan does not exist

```json
{
  "status_code": 404,
  "error": "subscription plan does not exist."
}
```

### Tasks

- [ ] Create an endpoint (Delete /api/v1/plans/{id}) to delete a subscription plan.
- [ ] Write unit tests for the endpoint.
- [ ] Write integration tests for the plan creation process.

### Testing

- [ ] Write unit tests for authorization and creating products.
- [ ] Write integration tests for the end-to-end process.
