### ISSUE TITLE
[FEAT]: Cancel Subscription Plan

### ISSUE THREAD

**Issue by Adewale66** [hngprojects/hng_boilerplate_java_web#205]
## Description

Develop Backend support to allow a user cancel their subscription plan.

## Acceptance Criteria

- Subscription plan must be valid.
- User must be authenticated.
- User must already have an active subscription plan.
- All unit and integration tests pass successfully.

### Error Handling:

- Log errors for invalid requests.
- Display clear error messages for invalid inputs.

## Purpose

To provide a user to cancel their subscription plan.

### Requirements

- User authenticated and authorized.
- Plan must be valid

### Expected Outcome

1. The backend should handle Pricing plan deletion efficiently.
2. The system should log responses and errors properly

## Endpoints

- Endpoint: ```  DELETE /api/v1/pricing/{id} ```

- #### Success Response: Cancel Pricing Plan 

```json
{
  "status_code": 200,
   "message" : "Your pricing plan has been cancelled and will expire on 12th March 2025"
}
```

- #### Error Response: Unauthorized Access

```json
{
  "status_code": 403,
  "error": "User is not authorized."
}
```

- #### Error Response: Pricing Plan does not exist

```json
{
  "status_code": 404,
  "error": "Pricing plan does not exist."
}
```

- #### Error Response: Pricing Plan has already been cancelled

```json
{
  "status_code": 409,
  "error": "Pricing plan has already been cancelled."
}
```

### Tasks

- [ ] Create an endpoint (Delete /api/v1/pricing/{id}) to cancel a subscription plan.
- [ ] Write unit tests for the endpoint.
- [ ] Write integration tests for the plan creation process.

### Testing

- [ ] Write unit tests for authorization and creating products.
- [ ] Write integration tests for the end-to-end process.
