### ISSUE TITLE
[FEAT] Get all Subscription Plans

### ISSUE THREAD

**Issue by Adewale66** [hngprojects/hng_boilerplate_java_web#228]
## Description

Develop backend support to retrieve all pricing plans.

## Acceptance Criteria

- All Subscription plans should be returned
- All unit and integration tests pass successfully.

### Security Measures:

- Use HTTPS for secure data transmission.
- Validate user input on the server side.

## Purpose

To provide retrieve all subscription plans.

### Requirements

- Develop server side logic to retrieve subscription plans from the database.

### Expected Outcome

1. The backend should return all plans.
2. The system should log responses and errors properly

## Endpoints

- Endpoint: ```  GET /api/v1/plans ```

- #### Success Response: Create Subscription Plan 

```json
 {
    [
        { 
         "id": "String",
        "name": "String",
        "description": "String",
        "price":  "float",
         "duration": "int"
       "duration_unit": "String"
      },
      { 
         "id": "String",
        "name": "String",
        "description": "String",
        "price":  "float",
         "duration": "int"
       "duration_unit": "String"
      },
   ]
}
```
### Tasks

- [ ] Create an endpoint (GET /api/v1/plans) to retrieve all subscription plans.
- [ ] Write unit tests for the endpoint.

### Testing

- [ ] Write unit tests for retrieving all plans.
