### ISSUE TITLE
Payment Integration with Multiple Payment Gateways

### ISSUE THREAD

**Issue by ZainabAlayande** [hngprojects/hng_boilerplate_java_web#267]
## Description
Implement the ability for users to make payments using multiple payment gateways such as Paystack, Flutterwave. This feature will enhance the user experience by providing flexibility in payment options and ensuring seamless transactions.

## Acceptance Criteria

- [ ] Users can configure and manage multiple payment gateways.
- [ ] Users can make payments using any of the configured payment gateways.
- [ ] The payment process is secure and prevents unauthorized transactions.
- [ ] Implement proper error handling and validation for payment information.
- [ ] Ensure the payment gateways adhere to best practices for security and user experience.

## Purpose

The goal is to provide users with various payment gateway options, enhancing both flexibility and user experience. By offering multiple payment gateways, users can choose the most convenient and secure method for their transactions.

## Requirements
- Implement a RESTful Endpoint for Payment Gateway Initialization
- Implement a RESTful Endpoint for Payment Processing.
- Implement proper error handling and validation for payment information.
- Ensure the payment process adheres to best practices for security and user experience.
- Write Unit Tests for individual components and services related to payment integration.

## Endpoints

**URL**

**1. PAYMENT INITIALIZATION**

**Authorization: Protected Endpoint**

- `Bearer _Authorized_User_Token_` 

```
/api/v1/payments/initiate
```

**METHOD**

```
POST
```

**Request Body**

- `amount (required):` The amount of the fee to be processed.
- `provider (required):` The payment provider of choice by user (Paystack, Flutterwave).

```
{
  "amount": 2000,
  "provider": "paystack" 
}
```

```
{
  "amount": 4600,
  "provider": "flutterwave" 
}
```

**RESPONSE**

****Success Response (json) - PAYSTACK****
```
{
  "status_code": 200,
  "message": "Paystack Payment Successfully Initialized",
  "data": {
       "reference": "jhs0mx9sdv",
       "authorization_url": "https://checkout.paystack.com/uu7eirjw4rg06n1"
  }
}
```

****Error Response (json) - PAYSTACK****
```
{
  "status_code": 400,
  "message": "Failed to initiate payment",
  "data": {}
}
```

****Success Response (json) - FLUTTERWAVE****
```
{
  "status_code": 200,
  "message": "Flutterwave Payment Successfully Initialized",
  "data": {
       "redirect_url": "https://ravemodal-dev.herokuapp.com/v3/hosted/pay/7bb53978ea95e4ea7aa8",
       "reference": "TRANS_9ac745a9-7862-4cef-b08c-8cd541d929c7"
  }
}
```

****Error Response (json) - FLUTTERWAVE****
```
{
  "status_code": 400,
  "message": "Failed to initiate payment",
  "data": {}
}
```

**2. PAYMENT VERIFICATION**

**Authorization: Protected Endpoint**

- `Bearer _Authorized_User_Token_` 

****PAYSTACK****

```
/api/v1/payments/verify/paystack?reference=8diabyehtd
```

****FLUTTERWAVE****
```
/api/v1/payments/verify/flutterwave?reference=TRANS_9ac745a9-7862-4cef-b08c-8cd541d929c7&status=completed&transactionId=6510195
```

**METHOD**

```
GET
```

**Request Param**

- `reference (required):` The payment reference to be verified. (Flutterwave and Paystack)
- `transactionId (required):` The payment reference to be verified. (Flutterwave only)
- `status (required):` The payment reference to be verified. (Flutterwave only)

**RESPONSE**

****Success Response (json) - PAYSTACK****
```
{
  "status_code": 200,
  "message": "Verification successful",
  "data": {
        "status": "success",
        "reference": "jhs0mx9sdv",
        "amount": "240000",
        "channel": "card",
        "currency": "NGN"
  }
}
```

****Error Response (json) - PAYSTACK****
```
{
  "status_code": 400,
  "message": "Payment verification failed",
  "data": {}
}
```

****Error Response (json) - PAYSTACK****
```
{
  "status_code": 404,
  "message": "Transaction not found",
  "data": {}
}
```

****Success Response (json) - FLUTTERWAVE****
```
{
  "status_code": 200,
  "message": "Verification successful",
  "data": {
       "status_code": "completed",
        "reference": "TRANS_9ac745a9-7862-4cef-b08c-8cd541d929c7",
        "amount": 2400,
        "currency": "NGN" 
  }
}
```

****Error Response (json) - FLUTTERWAVE****
```
{
  "status_code": 400,
  "message": "Payment verification failed",
  "data": {}
}
```

****Error Response (json) - FLUTTERWAVE****
```
{
  "status_code": 404,
  "message": "Transaction not found",
  "data": {}
}
```

**4. GET ALL PAYMENT FOR USER**

***URL***

```
/api/v1/payments/user
```

**Authorization: Protected Endpoint**

- `Bearer _Authorized_User_Token_` 

**METHOD**

```
GET
```

**RESPONSE BODY**

**Success Response**
```
{
    "status_code": "200",
    "message": "User payments successfully fetched",
    "data": [
        {
            "reference": "TRANS_9ac745a9-7862-4cef-b08c-8cd541d929c7",
            "amount": "2400.0000",
            "currency": "NGN",
            "status": "SUCCESSFUL",
            "paymentProvider": "FLUTTERWAVE"
        },
        {
            "reference": "jhs0mx9sdv",
            "amount": "240000.0000",
            "currency": "NGN",
            "status": "SUCCESSFUL",
            "paymentProvider": "PAYSTACK"
        },
        ........

    ]
}
```

**Error Response**
```
{
    "status_code": "401",
    "message": "Unauthorized",
    "data": {}
}
```

**4. GET SINGLE PAYMENT BY REFERENCE**

***URL***

```
api/v1/payments/reference/{reference}
```

**Authorization: Protected Endpoint**

- `Bearer _Authorized_User_Token_` 

**METHOD**

```
GET
```

**RESPONSE BODY**
```
{
    "status_code": "200",
    "message": "Payment fetched successfully",
    "data": {
        "reference": "TRANS_9ac745a9-7862-4cef-b08c-8cd541d929c7",
        "amount": "2400.0000",
        "currency": "NGN",
        "status": "SUCCESSFUL",
        "paymentProvider": "FLUTTERWAVE"
    }
}
```

## TASK

- [ ]  Design the payment gateway setup endpoints for Paystack, Flutterwave.
- [ ]  Implement the payment gateway setup flow, allowing users to configure their preferred payment gateways.
- [ ]  Implement the payment processing flow, allowing users to make payments using their configured payment gateways.
- [ ]  Integrate the payment endpoints with the existing user database to validate and update user payment records.
- [ ]  Implement secure handling and storage of payment information.
- [ ]  Implement error handling and validation for payment information and user requests.
- [ ]  Write unit tests for the payment functionality.

## Expected Outcome

- Functional payment gateway endpoints that meet all acceptance criteria.
- Users can securely set up and use multiple payment gateways (Paystack, Flutterwave).
- Payment information is handled securely and stored appropriately.
- The system accurately processes payment requests based on the provided payment information.
