### ISSUE TITLE
[FEAT] Get all email templates

### ISSUE THREAD

**Issue by Adewale66** [hngprojects/hng_boilerplate_java_web#357]
## Description

Develop backend support to retrieve all email templates.

## Acceptance Criteria

- All email templates should be returned
- All unit and integration tests pass successfully.

## Purpose

To  retrieve all email templates.

### Expected Outcome

1. The backend should return all email templates.
2. The system should log responses and errors properly

## Endpoints

- Endpoint: ```  GET /api/v1/email-templates ```

```json
 {
    [
        { 
         "id": "String",
        "title": "String",
        "template": "String",
        "status":  "string",
         "type": "string"
       "created_at": "date",
        "updated_at": "date"
      }
   ]
}
```
### Tasks

- [ ] Create an endpoint (GET /api/v1/email-templates) to retrieve all subscription plans.
- [ ] Write unit tests for the endpoint.

### Testing

- [ ] Write unit tests for retrieving all email templates.
