### ISSUE TITLE
[FEAT]: API Endpoint for Creating Roles within an Organisation

### ISSUE THREAD

**Issue by trini7y** [hngprojects/hng_boilerplate_java_web#385]
# Description
Develop and integrate an API endpoint to facilitate the creation of roles within an organization

### Scope:
- Design and implement a RESTful API endpoint for role creation
- Use `OrganizationGuard` to handle organization context
- Ensure proper authentication and authorization checks
- Validate input data and handle edge cases
- Implement necessary database operations
- Provide appropriate error handling and response formatting

### Specific Requirements:
- Implement `POST /api/v1/organisation/{:org-id}/roles` endpoint
- Use `OrganizationGuard` to extract and validate organization context
- Ensure authentication using JWT tokens
- Authorize users based on their permissions within the organization
- Validate input:
  - `name`: required, unique within org, max 50 characters
  - `description`: optional, max 200 characters
  - `permissions`: array of valid permission IDs
- Create role in database if all checks pass

### Request Body:
```json
{ 
  "name": "string",
  "description": "string"
}
```

### Request Body:
```json
{ 
  "name": "string",
  "description": "string"
}
```
### Success Response (201 Created)

```json
{ 
  "id": "string", 
  "name": "string", 
  "description": "string",
  "message": "Role created successfully" 
}
```
### Error Responses
#400 Bad Request (Invalid Input)

```json
{
  "status_code": 400,
  "error": "Invalid input",
  "message": "Detailed error message"
}
```

### 409 Conflict (Duplicate Role)

```json
{
  "status_code": 409,
  "error": "Conflict",
  "message": "A role with this name already exists in the organization"
}
```

### Tasks

- [ ] Set up endpoint for role creation
- [ ] Implement OrganizationGuard
- [ ] Authentication and Authorization of roles endpoints
- [ ] Validate all input required for creating roles
- [ ] Implement the required logic and database schema required for role creation
- [ ] Create custom exception to handle various error scenarios

### Testing

- [ ] Write unit tests for the role creation endpoint
- [ ] Write integration tests for the role creation endpoint
- [ ] Write tests for all instances of creating roles
