### ISSUE TITLE
[FEAT]: Endpoint to Retrieve a Single User by ID

### ISSUE THREAD

**Issue by ZainabAlayande** [hngprojects/hng_boilerplate_java_web#416]
## Description

Develop an API endpoint that retrieves a single user record by their ID. This endpoint should handle fetching the user details and returning them in a structured format.

## Acceptance Criteria
- The endpoint should be accessible via `api/v1/users/me/{id}` and accept HTTP GET requests.
- The endpoint should require authentication, and the requester must have the necessary permissions to view user details.
- The API should validate the user ID and return appropriate responses based on the operation's success or failure.

## Endpoint

**URL**

**1.  GET SINGLE USER BY ID**

```
api/v1/users/me/{id}
```

**METHOD**

```
GET
```

**RESPONSE**

****Success Response (json)****
```
{
  "status": "success",
  "message": "User data successfully fetched",
  "data": {
    "id": "123",
    "fullname": "John Doe",
    "email": "john.doe@example.com",
    "username": "johndoe",
    "role": "USER",
    "createdAt": "2024-08-05T12:05:38.000Z"
  }
}

```

****Error Response (json)****
```
{
  "status": "404",
  "message": "User not found with id: 123",
  "data": {}
}

```

```
{
  "status": "401",
  "message": "Unauthorized. You do not have the necessary permissions.",
  "data": {}
}

```

## TASK

- [ ] Implement the GET endpoint to retrieve a user by their ID.
- [ ] Ensure that the user ID is valid and exists in the database.
- [ ] Implement authentication and authorization checks to ensure the requester has the necessary permissions.
- [ ] Return appropriate success and error responses based on the outcome of the request.
- [ ] Write unit tests to cover successful retrieval, invalid user ID, and unauthorized access.
- [ ] Write end-to-end tests to verify the complete workflow of retrieving a user by ID.

## Expected Outcome

- A functional API endpoint that retrieves a user by their ID and returns their details in the specified format.
- The system should handle various scenarios, including success, user not found, and unauthorized access, with appropriate responses.
