### ISSUE TITLE
[FEAT]: Implement Endpoints to Compress Video

### ISSUE THREAD

**Issue by ZainabAlayande** [hngprojects/hng_boilerplate_java_web#529]
## Description:

This PR introduces two API endpoints for managing video compression:

POST `/api/v1/videos/compress` - Submits a request to start the video compression process.
GET `/api/v1/videos/compressed/download/{jobId}` - Allows the download of the compressed video file once the compression task is completed.

## Purpose:

**These endpoints allow users to:**

- Initiate Video Compression: Submit videos for compression with customizable options like resolution, bitrate, and output format.
- Download Compressed Videos: Access and download the compressed video files once the processing is completed successfully.

#### 1. POST `/api/v1/videos/compress`

**Description:** This endpoint accepts a request to initiate video compression. Users can specify options such as resolution, bitrate, and output format. The endpoint supports batch processing. Upon successful submission, the endpoint returns an acknowledgment along with a `jobId` that can be used to track the compression status.

**Request Param:**
- `video: (required)` "file1.mp4"
- `resolution: (optional)` "1920x1080" || "1280x720" || "640x360"
- `bitrate: (optional)` HIGH || MEDIM || LOW
- `outputFormat: (required)` mp4
    
**Details:**
- video: The video files to be processed.
- resolution: The desired resolution for the output video. Options typically include "1920x1080" (HIGH), "1280x720" (MEDIUM), and "640x360" (LOW).
- bitrate: The target bitrate for the compressed video. This affects the quality and file size, with options like HIGH, MEDIUM, or LOW.
- outputFormat: Specifies the desired format for the output video. 

**Response:**
```
{
    "message": "Job Created",
    "statusCode": 201,
    "data": {
        "jobId": "814c659d-a4bc-4a01-bf41-06c737277573",
        "status": "Pending",
        "message": "Pending",
        "filename": "VID-20240812-WA0025.mp4",
        "jobType": "Compress video",
        "progress": 0,
        "currentProcess": "Pending"
    }
}
```

#### 2. GET `/api/v1/videos/compressed/download/{jobId}`

**Description:** 
This endpoint retrieves the status or result of a specific video compression task identified by `{id}`.

**Response:**
```
Content-Type: video/mp4
```

## TASKS

- [ ] Implement the `POST /api/v1/videos/compress` endpoint to submit a video compression request.
- [ ]  Implement the `GET /api/v1/videos/{jobId}/compress/download` endpoint to download the compressed video by returning the video file directly.
- [ ]  Ensure that each endpoint handles appropriate success and error responses based on the outcome of the request.
- [ ]  Ensure that the compressed video is stored in a specified directory and create the directory if it doesn't exist.
- [ ]  Implement logic to publish the compression result to a queue once compression is complete.
- [ ]  Implement a consumer to listen to the queue, decode the video, and store it in the correct directory for future download.

## Expected Outcome

- A set of functional API endpoints for submitting video compression requests, checking the status of the compression task, and downloading the compressed video.
- The system should handle various scenarios, including successful compression, status retrieval, video download, and appropriate error handling with relevant responses.
