### ISSUE TITLE
[FEAT]: Implement endpoint to convert video format

### ISSUE THREAD

**Issue by Ofektom** [hngprojects/hng_boilerplate_java_web#545]
## Description:

This feature is implemented to convert video format into 4 types viz, MP4, AVI, MOV and MKV

## Purpose:

**These endpoints allow users to:**

- upload video and select set the conversion type to make a request.
- Download the converted video files once the processing is completed successfully.

## Endpoints:
 - Submits a request to start the video compression process.
#### GET `/api/v1/videos/{jobId}/download`

**Description:** This endpoint accepts a request to convert video. Users have to specify the output format, which is the conversion format . The endpoint takes one video per time and outputs one video in in the specified format.

**Request Param:**
- `video: (required)` "file1.mp4"
- `output_format: (required)` "avi, mov, or mkv"

**Response:**
```
{
    "message": "Job Created",
    "statusCode": 201,
    "success" true,
    "data": {
        "jobId": "814c659d-a4bc-4a01-bf41-06c737277573",
        "status": "Pending",
        "message": "Pending",
        "filename": "media_814c659d-a4bc-4a01-bf41-06c737277573"",
        "jobType": "convert video",
        "progress": 0,
        "currentProcess": "Pending"
        " media_format": mp4
        "expected_format": avi
    }
}
```

#### 2. GET `/api/v1/videos/{jobId}/download`

**Description:** 
This endpoint retrieves the status or result of a specific video compression task identified by `{id}`.

**Response:**
```
Content-Type: video/mp4
```

## TASKS

- [ ] Implement the `POST /api/v1/videos/convert` endpoint to submit a video conversion request.
- [ ]  Implement the `GET /api/v1/videos/{jobId}/download` endpoint to download the converted video by returning the video file directly.
- [ ]  Ensure that each endpoint handles appropriate success and error responses based on the outcome of the request.
- [ ]  Ensure that the converted video is stored in a specified directory and create the directory if it doesn't exist.
- [ ]  Implement logic to publish the converted result to a queue once compression is complete.
- [ ]  Implement a consumer to listen to the queue, decode the video, and store it in the correct directory for future download.

## Expected Outcome

- A set of functional API endpoints for submitting video conversion requests, checking the status of the conversion task, and downloading the converted or encoded video.
- The system should handle various scenarios, including successful conversion, status retrieval, video download, and appropriate error handling with relevant responses.
