### ISSUE TITLE
[FEAT] Implement API Endpoints for Creating Subscription Plans - BACKEND

### ISSUE THREAD

**Issue by Adewale66** [hngprojects/hng_boilerplate_java_web#6]
## Description

Develop backend support to create subscription plans. This feature will enable admin to create various plans.

## Acceptance Criteria

- Subscription plans can be created through the API.
- All unit and integration tests pass successfully.
- Both API and user documentation are updated to reflect the new subscription plan feature.

### Error Handling:

- Log errors for invalid requests.
- Display clear error messages for invalid inputs.

### Security Measures:

- Use HTTPS for secure data transmission.
- Validate user input on the server side.

## Purpose

To provide admin with the ability to create different subscription plans.

### Requirements

- Admin must be authenticated and authorized.
- Develop server side logic to add subscription plans to database.

### Expected Outcome

1. The backend should handle subscription plan creation efficiently.
2. The system should log responses and errors properly

### DB Schema

```mermaid
erDiagram
    Plan {
        varchar(255) id PK
        varchar(255) name
        int price
        int duration
        varchar(255) description
        varchar(255) duration_unit
    }
```

## Endpoints

- Endpoint: ```  POST /api/v1/plans ```

- #### Request Body:

 ```json
{
  "name": "String",
  "description": "String",
  "price": "float",
  "duration": "int",
  "duration_unit": "String"
}
```

- #### Success Response: Create Subscription Plan 

```json
 {
   "data": { 
     "id": "String",
     "name": "String",
     "description": "String",
     "price":  "float",
     "duration": "int"
     "duration_unit": "String"

  },
  "status_code": 201,
  "message" : "Plan created successfully"
}
```

- #### Error Response: Unauthorized Access

```json
{
  "status_code": 403,
  "error": "User is not authorized to create subscription plans."
}
```

- #### Error Response: Subscription Plan already exists

```json
{
  "status_code": 400,
  "error": "subscription plan already exists."
}
```

### Tasks

- [ ] Create an endpoint (POST /api/v1/plans) to create new subscription plans.
- [ ] Write unit tests for the endpoint.
- [ ] Write integration tests for the plan creation process.

### Testing

- [ ] Write unit tests for authorization and creating products.
- [ ] Write integration tests for the end-to-end process.
